# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Define a host for the ingress. It must match with the TLS certificate's host if present
host: "liqo-dashboard.top-ix.org"

image:
  # -- Pull polocy for dashboard pods
  pullPolicy: IfNotPresent
  # -- Tag to get other versions of the image
  tag: "0.5"

tls:
  # -- Name of the secret which contains the TLS certificate
  secretName: ""

backend:
  # -- Backend dashboard image name
  imageName: lucarocco97/liqo-dashboard-backend
  # -- Server's port
  port: 8080
  # -- Number of replicas of backend's pods
  replicas: 1
  service:
    # -- Type of service. A ClusterIP service is enough because we are using an ingress
    type: ClusterIP

frontend:
  # -- Google Analytics traking ID. It enables simple GA metrics such as number of visits
  gaTrackingID: ""
  # -- Frontend dashboard image name
  imageName: lucarocco97/liqo-dashboard-frontend
  # -- Frontend port
  port: 8080
  # -- Number of replicas of frontend's pods
  replicas: 1
  service:
    # -- Type of service. A ClusterIP service is enough because we are using an ingress
    type: ClusterIP

ingress:
  annotations: {}