{{- $clusterRoleBinding := (merge (dict "name" "clusterrolebinding" "module" "dashboard") .) -}}
{{- $serviceAccount := (merge (dict "name" "serviceaccount" "module" "dashboard") .) -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" $clusterRoleBinding }}
  labels:
    {{- include "chart.labels" $clusterRoleBinding | nindent 4}}
subjects:
  - namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
    name: {{ include "chart.prefixedName" $serviceAccount }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "chart.fullname" $clusterRoleBinding }}
